"""empty message

Revision ID: 517d0019564a
Revises: 0763d677d453
Create Date: 2025-08-29 14:56:11.956259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517d0019564a'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
